apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: nginx-deployment
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "573106849954.dkr.ecr.eu-central-1.amazonaws.com/flux-test:fb1c3fe"
          ports:
            - containerPort: 80
